StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6484D3ADFBD5A6FC}" {
   Id "RT_Radio-AntennaPropName"
   Target_en_us "Antenna with Radio"
   Target_ru_ru "Антенна с Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584623
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED04586E422}" {
   Id "RT_Radio-CannotPerform_Antenna"
   Target_en_us "No active radio antenna"
   Target_ru_ru "Нет активной радиоантенны"
   Modified 1705584648
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED081C1C732}" {
   Id "RT_Radio-CannotPerform_OneStation"
   Target_en_us "No other radio stations"
   Target_ru_ru "Нет других радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584655
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED07D269C42}" {
   Id "RT_Radio-CannotPerform_Radio"
   Target_en_us "Radio is broken"
   Target_ru_ru "Радио сломано"
   Status DEVELOPMENT_DONE
   Modified 1705584657
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED0B3BB4444}" {
   Id "RT_Radio-CannotPerform_Station"
   Target_en_us "No radio stations"
   Target_ru_ru "Нет радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584659
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{649F50FCD2539433}" {
   Id "RT_Radio-ResetActionName"
   Target_en_us "Punch radio to fix"
   Target_ru_ru "Ударить по радио для починки"
   Status DEVELOPMENT_DONE
   Modified 1705584661
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED364D7E339}" {
   Id "RT_Radio-OnOffActionName"
   Target_en_us "Radio"
   Target_ru_ru "Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584627
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED3743B271A}" {
   Id "RT_Radio-StationActionName"
   Target_en_us "Station"
   Target_ru_ru "Станция"
   Status DEVELOPMENT_DONE
   Modified 1705584633
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED349ECAA73}" {
   Id "RT_Radio-VolumeActionName"
   Target_en_us "Volume"
   Target_ru_ru "Громкость"
   Status DEVELOPMENT_DONE
   Modified 1705584640
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}