StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6484D3ADFBD5A6FC}" {
   Id "RT_AntennaPropName"
   Target_en_us "Antenna with Radio"
   Target_ru_ru "Антенна с Радио"
   Modified 1686452141
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED04586E422}" {
   Id "RT_Radio_CannotPerform_Antenna"
   Target_en_us "No active radio antenna"
   Target_ru_ru "Нет активной радиоантенны"
   Modified 1686453123
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED081C1C732}" {
   Id "RT_Radio_CannotPerform_OneStation"
   Target_en_us "No other radio stations"
   Target_ru_ru "Нет других радиостанций"
   Modified 1686453218
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED07D269C42}" {
   Id "RT_Radio_CannotPerform_Radio"
   Target_en_us "Radio is broken"
   Target_ru_ru "Радио сломано"
   Modified 1686453045
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED0B3BB4444}" {
   Id "RT_Radio_CannotPerform_Station"
   Target_en_us "No radio stations"
   Target_ru_ru "Нет радиостанций"
   Modified 1686453171
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{649F50FCD2539433}" {
   Id "RT_Radio_ResetActionName"
   Target_en_us "Punch radio"
   Target_ru_ru "Ударить по радио"
   Modified 1688166976
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED364D7E339}" {
   Id "RT_RadioOnOffActionName"
   Target_en_us "Radio"
   Target_ru_ru "Радио"
   Modified 1686452563
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED3743B271A}" {
   Id "RT_RadioStationActionName"
   Target_en_us "Station"
   Target_ru_ru "Станция"
   Modified 1686452597
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED349ECAA73}" {
   Id "RT_RadioVolumeActionName"
   Target_en_us "Volume"
   Target_ru_ru "Громкость"
   Modified 1686452630
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}