StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6484D3ADFBD5A6FC}" {
   Id "RT_PS-AntennaPropName"
   Target_en_us "Antenna with Radio"
   Target_ru_ru "Антенна с Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584623
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68BFE6DA41}" {
   Id "RT_PS-CallToRadioActionName"
   Target_en_us "Call to the radio"
   Target_ru_ru "Позвонить на радио"
   Modified 1707647852
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68B2793496}" {
   Id "RT_PS-CallToRadioAnswer"
   Target_en_us "Yes"
   Target_ru_ru "Да"
   Modified 1707647875
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D693DE83D79}" {
   Id "RT_PS-CallToRadioCancel"
   Target_en_us "Hang up"
   Target_ru_ru "Сбросить"
   Modified 1707648053
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68B635E387}" {
   Id "RT_PS-CallToRadioQuestion"
   Target_en_us "Want to change the track on the station?"
   Target_ru_ru "Желаете сменить трек на станции?"
   Modified 1707647976
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED04586E422}" {
   Id "RT_PS-CannotPerform_Antenna"
   Target_en_us "No active radio antenna"
   Target_ru_ru "Нет активной радиоантенны"
   Modified 1705584648
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED081C1C732}" {
   Id "RT_PS-CannotPerform_OneStation"
   Target_en_us "No other radio stations"
   Target_ru_ru "Нет других радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584655
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED07D269C42}" {
   Id "RT_PS-CannotPerform_Radio"
   Target_en_us "Radio is broken"
   Target_ru_ru "Радио сломано"
   Status DEVELOPMENT_DONE
   Modified 1705584657
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED0B3BB4444}" {
   Id "RT_PS-CannotPerform_Station"
   Target_en_us "No radio stations"
   Target_ru_ru "Нет радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584659
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C6C6D3118EA584}" {
   Id "RT_PS-Editor_Attribute_RadioState_Name"
   Target_en_us "Radio State"
   Target_ru_ru "Состояние радио"
   Modified 1724316470
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C700DF94F0CA55}" {
   Id "RT_PS-Editor_Attribute_RadioState_Off_Name"
   Target_en_us "Off"
   Target_ru_ru "Выкл"
   Modified 1724318661
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C700DF81C9CE04}" {
   Id "RT_PS-Editor_Attribute_RadioState_On_Name"
   Target_en_us "On"
   Target_ru_ru "Вкл"
   Modified 1724318640
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C700DF7156E1B2}" {
   Id "RT_PS-Editor_Attribute_RadioStation_Name"
   Target_en_us "Station"
   Target_ru_ru "Станция"
   Modified 1724318613
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C700DF7F6CDF0B}" {
   Id "RT_PS-Editor_Attribute_RadioVolume_Name"
   Target_en_us "Volume"
   Target_ru_ru "Громкость"
   Modified 1724318592
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C70435CC67170E}" {
   Id "RT_PS-Editor_ContextAction_ChangeStation_Name"
   Target_en_us "Change radio station"
   Target_ru_ru "Сменить радиостанцию"
   Modified 1724322376
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C70437B400F433}" {
   Id "RT_PS-Editor_ContextAction_FixRadio_Name"
   Target_en_us "Fix radio"
   Target_ru_ru "Починить радио"
   Modified 1724322596
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{66C70435936EE2A6}" {
   Id "RT_PS-Editor_ContextAction_ToggleRadio_Name"
   Target_en_us "Toggle Radio"
   Target_ru_ru "Переключить радио"
   Modified 1724321366
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{685CF10A5560511A}" {
   Id "RT_PS-Item_PortableRadio_Description"
   Target_en_us "Take your favorite stations with you!"
   Target_ru_ru "Возьмите с собой свои любимые радиостанции!"
   Modified 1750926519
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{685CF10A5F63DF0A}" {
   Id "RT_PS-Item_PortableRadio_Name"
   Target_en_us "Portable Radio"
   Target_ru_ru "Портативное радио"
   Modified 1750926534
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED364D7E339}" {
   Id "RT_PS-OnOffActionName"
   Target_en_us "Radio"
   Target_ru_ru "Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584627
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65AF622DF98AEA37}" {
   Id "RT_PS-RadioVolumeSetting"
   Target_en_us "Radio volume boost"
   Target_ru_ru "Буст громкости радио"
   Modified 1705993250
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{649F50FCD2539433}" {
   Id "RT_PS-ResetActionName"
   Target_en_us "Punch radio to fix"
   Target_ru_ru "Ударить по радио для починки"
   Status DEVELOPMENT_DONE
   Modified 1705584661
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED3743B271A}" {
   Id "RT_PS-StationActionName"
   Target_en_us "Station"
   Target_ru_ru "Станция"
   Status DEVELOPMENT_DONE
   Modified 1705584633
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED349ECAA73}" {
   Id "RT_PS-VolumeActionName"
   Target_en_us "Volume"
   Target_ru_ru "Громкость"
   Status DEVELOPMENT_DONE
   Modified 1705584640
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}