StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6484D3ADFBD5A6FC}" {
   Id "RT_PS-AntennaPropName"
   Target_en_us "Antenna with Radio"
   Target_ru_ru "Антенна с Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584623
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68BFE6DA41}" {
   Id "RT_PS-CallToRadioActionName"
   Target_en_us "Call to the radio"
   Target_ru_ru "Позвонить на радио"
   Modified 1707647852
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68B2793496}" {
   Id "RT_PS-CallToRadioAnswer"
   Target_en_us "Yes"
   Target_ru_ru "Да"
   Modified 1707647875
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D693DE83D79}" {
   Id "RT_PS-CallToRadioCancel"
   Target_en_us "Hang up"
   Target_ru_ru "Сбросить"
   Modified 1707648053
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65C89D68B635E387}" {
   Id "RT_PS-CallToRadioQuestion"
   Target_en_us "Want to change the track on the station?"
   Target_ru_ru "Желаете сменить трек на станции?"
   Modified 1707647976
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED04586E422}" {
   Id "RT_PS-CannotPerform_Antenna"
   Target_en_us "No active radio antenna"
   Target_ru_ru "Нет активной радиоантенны"
   Modified 1705584648
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED081C1C732}" {
   Id "RT_PS-CannotPerform_OneStation"
   Target_en_us "No other radio stations"
   Target_ru_ru "Нет других радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584655
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED07D269C42}" {
   Id "RT_PS-CannotPerform_Radio"
   Target_en_us "Radio is broken"
   Target_ru_ru "Радио сломано"
   Status DEVELOPMENT_DONE
   Modified 1705584657
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED0B3BB4444}" {
   Id "RT_PS-CannotPerform_Station"
   Target_en_us "No radio stations"
   Target_ru_ru "Нет радиостанций"
   Status DEVELOPMENT_DONE
   Modified 1705584659
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED364D7E339}" {
   Id "RT_PS-OnOffActionName"
   Target_en_us "Radio"
   Target_ru_ru "Радио"
   Status DEVELOPMENT_DONE
   Modified 1705584627
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{65AF622DF98AEA37}" {
   Id "RT_PS-RadioVolumeSetting"
   Target_en_us "Radio volume boost"
   Target_ru_ru "Буст громкости радио"
   Modified 1705993250
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{649F50FCD2539433}" {
   Id "RT_PS-ResetActionName"
   Target_en_us "Punch radio to fix"
   Target_ru_ru "Ударить по радио для починки"
   Status DEVELOPMENT_DONE
   Modified 1705584661
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED3743B271A}" {
   Id "RT_PS-StationActionName"
   Target_en_us "Station"
   Target_ru_ru "Станция"
   Status DEVELOPMENT_DONE
   Modified 1705584633
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
  CustomStringTableItem "{64852ED349ECAA73}" {
   Id "RT_PS-VolumeActionName"
   Target_en_us "Volume"
   Target_ru_ru "Громкость"
   Status DEVELOPMENT_DONE
   Modified 1705584640
   Author "Kompoman32"
   LastChanged "Kompoman32"
  }
 }
}